config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    resources :posts

    member do
      post 'join'
      post 'quit'
    end
  end

  namespace :account do
    resources :groups
    resources :posts
  end

  root 'groups#index'
end

app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :posts

  has_many :group_users
  has_many :members, through: :group_users, source: :user

  after_create :join_owner_to_group

  def editable_by?(user)
    user && user == owner
  end

  def join_owner_to_group
    members << owner
  end

end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base

  belongs_to :group
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :group, counter_cache: true
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  def editable_by?(user)
    user && user == author
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # We use exclamation "!" at the end of method because we are going to alter this object.
  # We use exclamation "?" at the end of method because we are going to return boolean value.

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

  def is_member_of?(group)
    participated_groups.include?(group)
  end

end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController

  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.order("posts_count DESC")
  end

end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

  before_action :authenticate_user!

  def index
    @posts = current_user.posts.order("updated_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_group, only: [:show, :join, :quit]

  def join
    if current_user.is_member_of?(@group)
      flash[:warning] = "You're already a member of this group."
    else
      current_user.join!(@group)
    end
    redirect_to group_path(@group)
  end

  def quit
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
    else
      flash[:warning] = "You're not a member of this group."
    end
    redirect_to group_path(@group)
  end

  def index
    @groups = Group.all
  end

  def show
    @posts = @group.posts
  end

  def new
    @group = Group.new
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

private

  def group_params
    params.require(:group).permit(:name, :description)
  end

  def find_group
    @group = Group.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_group
  before_action :member_required, only: [:new, :create]

  def new
    @post = @group.posts.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = @group.posts.new(post_params)
    @post.author = current_user
    if @post.save

      # We used "counter_cache" instead of it.
      # Group.increment_counter(:posts_count, @group.id)
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    # We used "counter_cache" instead of it.
    # Group.decrement_counter(:posts_count, @group.id)

    redirect_to group_path(@group)
  end

private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_required
    unless current_user.is_member_of?(@group)
      flash[:warning] = "You're not a member of this group! Can't post."
      redirect_to group_path(@group)
    end
  end

end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Groupme', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Group', account_groups_path %></li>
              <li><%= link_to 'My Post', account_posts_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/groups/edit.html.erb
<div class="container">
  <%= simple_form_for @group do |f| %>
    <%= f.input :name, required: true %>
    <%= f.input :description, as: :text, required: true %>
    <%= f.button :submit, data: { disable_with: "Submiting..." } %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="container">
  <h1>All groups</h1>
  <%= link_to 'New Group', new_group_path %>
  <ul class="all-groups-block">
    <% @groups.each do |group| %>
      <li class="the-group"><h2><%= link_to truncate(group.name, length: 17), group_path(group) %></h2></li>
      <% if current_user && group.editable_by?(current_user) %>
        <%= link_to 'Edit', edit_group_path(group) %>
        <%= link_to 'Delete', group_path(group), method: 'delete', data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/groups/new.html.erb
<div class="container">
  <%= simple_form_for @group do |f| %>
    <%= f.input :name, required: true %>
    <%= f.input :description, as: :text, required: true %>
    <%= f.button :submit, data: { disable_with: 'Submiting...' } %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="container">
  <h1><%= @group.name %></h1>
  <%= link_to 'Join Group', join_group_path(@group), method: :post %>
  <%= link_to 'Quit Group', quit_group_path(@group), method: :post %>
  <p><%= @group.description %></p>
  <hr>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= simple_format(post.content) %> - <strong><%= post.author.name %></strong>
        <% if current_user && post.editable_by?(current_user) %>
          <%= link_to 'Edit', edit_group_post_path(post.group, post) %>
          <%= link_to 'Delete', group_post_path(post.group, post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <% if current_user && current_user.is_member_of?(@group) %>
    <%= link_to 'New Post', new_group_post_path(@group) %>
  <% end %>
  <%= link_to 'Group List', groups_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'common/menu' %>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <%= simple_form_for [@group, @post] do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.button :submit, data: { disable_with: 'Submiting...' } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= simple_form_for [@group, @post] do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.button :submit, data: { disable_with: 'Submiting...' } %>
  <% end %>
</div>